/*
Product Management API

API for managing products, including adding, updating, and retrieving products and their variants.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiProductsGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiProductsGet200ResponseData{}

// ApiProductsGet200ResponseData struct for ApiProductsGet200ResponseData
type ApiProductsGet200ResponseData struct {
	Data []map[string]interface{} `json:"data,omitempty"`
	Pagination *ApiProductsGet200ResponseDataPagination `json:"pagination,omitempty"`
}

// NewApiProductsGet200ResponseData instantiates a new ApiProductsGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiProductsGet200ResponseData() *ApiProductsGet200ResponseData {
	this := ApiProductsGet200ResponseData{}
	return &this
}

// NewApiProductsGet200ResponseDataWithDefaults instantiates a new ApiProductsGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiProductsGet200ResponseDataWithDefaults() *ApiProductsGet200ResponseData {
	this := ApiProductsGet200ResponseData{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApiProductsGet200ResponseData) GetData() []map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiProductsGet200ResponseData) GetDataOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApiProductsGet200ResponseData) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []map[string]interface{} and assigns it to the Data field.
func (o *ApiProductsGet200ResponseData) SetData(v []map[string]interface{}) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ApiProductsGet200ResponseData) GetPagination() ApiProductsGet200ResponseDataPagination {
	if o == nil || IsNil(o.Pagination) {
		var ret ApiProductsGet200ResponseDataPagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiProductsGet200ResponseData) GetPaginationOk() (*ApiProductsGet200ResponseDataPagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ApiProductsGet200ResponseData) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given ApiProductsGet200ResponseDataPagination and assigns it to the Pagination field.
func (o *ApiProductsGet200ResponseData) SetPagination(v ApiProductsGet200ResponseDataPagination) {
	o.Pagination = &v
}

func (o ApiProductsGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiProductsGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableApiProductsGet200ResponseData struct {
	value *ApiProductsGet200ResponseData
	isSet bool
}

func (v NullableApiProductsGet200ResponseData) Get() *ApiProductsGet200ResponseData {
	return v.value
}

func (v *NullableApiProductsGet200ResponseData) Set(val *ApiProductsGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableApiProductsGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableApiProductsGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiProductsGet200ResponseData(val *ApiProductsGet200ResponseData) *NullableApiProductsGet200ResponseData {
	return &NullableApiProductsGet200ResponseData{value: val, isSet: true}
}

func (v NullableApiProductsGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiProductsGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


