/*
Product Management API

API for managing products, including adding, updating, and retrieving products and their variants.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiProductsGet200ResponseDataPagination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiProductsGet200ResponseDataPagination{}

// ApiProductsGet200ResponseDataPagination struct for ApiProductsGet200ResponseDataPagination
type ApiProductsGet200ResponseDataPagination struct {
	CurrentPage *int32 `json:"current_page,omitempty"`
	PerPage *int32 `json:"per_page,omitempty"`
	TotalProducts *int32 `json:"total_products,omitempty"`
	TotalPages *int32 `json:"total_pages,omitempty"`
}

// NewApiProductsGet200ResponseDataPagination instantiates a new ApiProductsGet200ResponseDataPagination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiProductsGet200ResponseDataPagination() *ApiProductsGet200ResponseDataPagination {
	this := ApiProductsGet200ResponseDataPagination{}
	return &this
}

// NewApiProductsGet200ResponseDataPaginationWithDefaults instantiates a new ApiProductsGet200ResponseDataPagination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiProductsGet200ResponseDataPaginationWithDefaults() *ApiProductsGet200ResponseDataPagination {
	this := ApiProductsGet200ResponseDataPagination{}
	return &this
}

// GetCurrentPage returns the CurrentPage field value if set, zero value otherwise.
func (o *ApiProductsGet200ResponseDataPagination) GetCurrentPage() int32 {
	if o == nil || IsNil(o.CurrentPage) {
		var ret int32
		return ret
	}
	return *o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiProductsGet200ResponseDataPagination) GetCurrentPageOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentPage) {
		return nil, false
	}
	return o.CurrentPage, true
}

// HasCurrentPage returns a boolean if a field has been set.
func (o *ApiProductsGet200ResponseDataPagination) HasCurrentPage() bool {
	if o != nil && !IsNil(o.CurrentPage) {
		return true
	}

	return false
}

// SetCurrentPage gets a reference to the given int32 and assigns it to the CurrentPage field.
func (o *ApiProductsGet200ResponseDataPagination) SetCurrentPage(v int32) {
	o.CurrentPage = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *ApiProductsGet200ResponseDataPagination) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiProductsGet200ResponseDataPagination) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *ApiProductsGet200ResponseDataPagination) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *ApiProductsGet200ResponseDataPagination) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetTotalProducts returns the TotalProducts field value if set, zero value otherwise.
func (o *ApiProductsGet200ResponseDataPagination) GetTotalProducts() int32 {
	if o == nil || IsNil(o.TotalProducts) {
		var ret int32
		return ret
	}
	return *o.TotalProducts
}

// GetTotalProductsOk returns a tuple with the TotalProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiProductsGet200ResponseDataPagination) GetTotalProductsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalProducts) {
		return nil, false
	}
	return o.TotalProducts, true
}

// HasTotalProducts returns a boolean if a field has been set.
func (o *ApiProductsGet200ResponseDataPagination) HasTotalProducts() bool {
	if o != nil && !IsNil(o.TotalProducts) {
		return true
	}

	return false
}

// SetTotalProducts gets a reference to the given int32 and assigns it to the TotalProducts field.
func (o *ApiProductsGet200ResponseDataPagination) SetTotalProducts(v int32) {
	o.TotalProducts = &v
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *ApiProductsGet200ResponseDataPagination) GetTotalPages() int32 {
	if o == nil || IsNil(o.TotalPages) {
		var ret int32
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiProductsGet200ResponseDataPagination) GetTotalPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPages) {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *ApiProductsGet200ResponseDataPagination) HasTotalPages() bool {
	if o != nil && !IsNil(o.TotalPages) {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given int32 and assigns it to the TotalPages field.
func (o *ApiProductsGet200ResponseDataPagination) SetTotalPages(v int32) {
	o.TotalPages = &v
}

func (o ApiProductsGet200ResponseDataPagination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiProductsGet200ResponseDataPagination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrentPage) {
		toSerialize["current_page"] = o.CurrentPage
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if !IsNil(o.TotalProducts) {
		toSerialize["total_products"] = o.TotalProducts
	}
	if !IsNil(o.TotalPages) {
		toSerialize["total_pages"] = o.TotalPages
	}
	return toSerialize, nil
}

type NullableApiProductsGet200ResponseDataPagination struct {
	value *ApiProductsGet200ResponseDataPagination
	isSet bool
}

func (v NullableApiProductsGet200ResponseDataPagination) Get() *ApiProductsGet200ResponseDataPagination {
	return v.value
}

func (v *NullableApiProductsGet200ResponseDataPagination) Set(val *ApiProductsGet200ResponseDataPagination) {
	v.value = val
	v.isSet = true
}

func (v NullableApiProductsGet200ResponseDataPagination) IsSet() bool {
	return v.isSet
}

func (v *NullableApiProductsGet200ResponseDataPagination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiProductsGet200ResponseDataPagination(val *ApiProductsGet200ResponseDataPagination) *NullableApiProductsGet200ResponseDataPagination {
	return &NullableApiProductsGet200ResponseDataPagination{value: val, isSet: true}
}

func (v NullableApiProductsGet200ResponseDataPagination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiProductsGet200ResponseDataPagination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


