/*
Product Management API

API for managing products, including adding, updating, and retrieving products and their variants.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAddSimpleProductPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAddSimpleProductPost200Response{}

// ApiAddSimpleProductPost200Response struct for ApiAddSimpleProductPost200Response
type ApiAddSimpleProductPost200Response struct {
	Message *string `json:"message,omitempty"`
	Data *ApiAddSimpleProductPost200ResponseData `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// NewApiAddSimpleProductPost200Response instantiates a new ApiAddSimpleProductPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAddSimpleProductPost200Response() *ApiAddSimpleProductPost200Response {
	this := ApiAddSimpleProductPost200Response{}
	return &this
}

// NewApiAddSimpleProductPost200ResponseWithDefaults instantiates a new ApiAddSimpleProductPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAddSimpleProductPost200ResponseWithDefaults() *ApiAddSimpleProductPost200Response {
	this := ApiAddSimpleProductPost200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ApiAddSimpleProductPost200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddSimpleProductPost200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ApiAddSimpleProductPost200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ApiAddSimpleProductPost200Response) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApiAddSimpleProductPost200Response) GetData() ApiAddSimpleProductPost200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ApiAddSimpleProductPost200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddSimpleProductPost200Response) GetDataOk() (*ApiAddSimpleProductPost200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApiAddSimpleProductPost200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ApiAddSimpleProductPost200ResponseData and assigns it to the Data field.
func (o *ApiAddSimpleProductPost200Response) SetData(v ApiAddSimpleProductPost200ResponseData) {
	o.Data = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ApiAddSimpleProductPost200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAddSimpleProductPost200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ApiAddSimpleProductPost200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ApiAddSimpleProductPost200Response) SetSuccess(v bool) {
	o.Success = &v
}

func (o ApiAddSimpleProductPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAddSimpleProductPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableApiAddSimpleProductPost200Response struct {
	value *ApiAddSimpleProductPost200Response
	isSet bool
}

func (v NullableApiAddSimpleProductPost200Response) Get() *ApiAddSimpleProductPost200Response {
	return v.value
}

func (v *NullableApiAddSimpleProductPost200Response) Set(val *ApiAddSimpleProductPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAddSimpleProductPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAddSimpleProductPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAddSimpleProductPost200Response(val *ApiAddSimpleProductPost200Response) *NullableApiAddSimpleProductPost200Response {
	return &NullableApiAddSimpleProductPost200Response{value: val, isSet: true}
}

func (v NullableApiAddSimpleProductPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAddSimpleProductPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


