/*
Product Management API

API for managing products, including adding, updating, and retrieving products and their variants.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiProductsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiProductsGet200Response{}

// ApiProductsGet200Response struct for ApiProductsGet200Response
type ApiProductsGet200Response struct {
	Data *ApiProductsGet200ResponseData `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// NewApiProductsGet200Response instantiates a new ApiProductsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiProductsGet200Response() *ApiProductsGet200Response {
	this := ApiProductsGet200Response{}
	return &this
}

// NewApiProductsGet200ResponseWithDefaults instantiates a new ApiProductsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiProductsGet200ResponseWithDefaults() *ApiProductsGet200Response {
	this := ApiProductsGet200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApiProductsGet200Response) GetData() ApiProductsGet200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ApiProductsGet200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiProductsGet200Response) GetDataOk() (*ApiProductsGet200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApiProductsGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ApiProductsGet200ResponseData and assigns it to the Data field.
func (o *ApiProductsGet200Response) SetData(v ApiProductsGet200ResponseData) {
	o.Data = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ApiProductsGet200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiProductsGet200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ApiProductsGet200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ApiProductsGet200Response) SetSuccess(v bool) {
	o.Success = &v
}

func (o ApiProductsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiProductsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableApiProductsGet200Response struct {
	value *ApiProductsGet200Response
	isSet bool
}

func (v NullableApiProductsGet200Response) Get() *ApiProductsGet200Response {
	return v.value
}

func (v *NullableApiProductsGet200Response) Set(val *ApiProductsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiProductsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiProductsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiProductsGet200Response(val *ApiProductsGet200Response) *NullableApiProductsGet200Response {
	return &NullableApiProductsGet200Response{value: val, isSet: true}
}

func (v NullableApiProductsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiProductsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


